### ISSUE TITLE
Any plan to support transmission 4.0?

### ISSUE THREAD

**Issue by hexian000** [y-polek/TransmissionRemote#124]
This app seems not working with latest transmission.

Thanks for your efforts, I've been a user for years.

**Comment by y-polek** [comment]
@hexian000 What is your setup?
On my side, it works fine with Transmission 4.0.5 on macOS and 4.0.4 on Linux

**Comment by peerless2012** [comment]
It works for me, tr 4.0.5 for linux.

**Comment by hexian000** [comment]
> @hexian000 What is your setup? On my side, it works fine with Transmission 4.0.5 on macOS and 4.0.4 on Linux

I'm using an image from https://hub.docker.com/r/linuxserver/transmission

When version 4.0 is just relesed, I made a check. At that time the web UI was working but RPC was not, so I get back to the tag version-3.00-r8.

But when I pulled the latest(4.0.5) release and checked again everything just works. Sorry for my mistake. XD

Thank you again for this handy app~
