### ISSUE TITLE
Req: Option to disable the Floating Action Button

### ISSUE THREAD

**Issue by nx6** [y-polek/TransmissionRemote#67]
Pretty simple request. I add torrents from web page links or other methods outside the app, and rarely need to do it from within, so I'd rather not have that new floaty button on top of my display. Can you add a checkbox to the prefs to hide it?

Love the new Night Mode, btw.

**Comment by y-polek** [comment]
ec434f60cb51b53250ac51ca920ec2ebbe43a09d
