### ISSUE TITLE
Unable to add udp tracker

### ISSUE THREAD

**Issue by bassmadrigal** [y-polek/TransmissionRemote#78]
I tried adding two udp trackers to an entry today, yet the client seems to force http addresses. I tried adding ```udp://tracker.coppersurfer.tk:6969/announce``` which showed up in the app as: ```http://udp:80```

I think because of the URL parsing, it dropped the hostname and port number and defaulted to port 80. It'd be awesome if support for adding udp trackers could be added to the app.

Thanks for your work so far!
Jeremy

Edit: I just noticed that it does add the full url, but adds http:// in front of it, which obviously causes the URL to be invalid. It seems the parser to display the URL within the app is what displays ```http://udp:80```, yet in transmission, it will be ```http://udp://tracker.coppersurfer.tk:6969/announce```

**Comment by y-polek** [comment]
Thanks for pull request.
Merged into develop branch
