### ISSUE TITLE
License of the project?

### ISSUE THREAD

**Issue by Poussinou** [y-polek/TransmissionRemote#92]
What's the license of this project? I would suggest GNU GPL v3 if it's ok for you.

This has to be discussed before adding the app to F-Droid #68

**Comment by y-polek** [comment]
I'd prefer to use [Apache 2.0](https://www.gnu.org/licenses/license-list.html#apache2) license.
It is also compatible with F-Droid.

**Comment by Poussinou** [comment]
That's ok too yes :)

could you add it to the repo?

**Comment by PeterDaveHello** [comment]
I can help add it. Just need to figure out a small issue here first: #94 :smile:

**Comment by Poussinou** [comment]
You have to ask all the [contributors](https://github.com/y-polek/TransmissionRemote/graphs/contributors) first to have their agreement about the new license.

**Comment by Poussinou** [comment]
@hrko99 @hell0-Wor1d @gumblex @alexiri @sarbyn @aldur @gH0StArthour @pablogventura 

Is it ok for you to switch the license to Apache 2.0 ? Please comment yes if you agree, so that we can add this app to F-Droid :)

**Comment by aldur** [comment]
I agree, and thank you all for your work.

**Comment by hrko** [comment]
yes

**Comment by gumblex** [comment]
yes

**Comment by alexiri** [comment]
Ok with me

**Comment by pablogventura** [comment]
No problem

**Comment by sarbyn** [comment]
No problem!

**Comment by khimaros** [comment]
Is anything else blocking this?

Would you be willing to accept a PR that adds a LICENSE file (Apache 2.0) to this repo?

**Comment by y-polek** [comment]
Added Apache 2.0 License.
Thank you, everyone, who contributed to the project.
