### ISSUE TITLE
Add 'Share' action

### ISSUE THREAD

**Issue by pataquets** [y-polek/TransmissionRemote#93]
Either the torrent file or the magnet link. Better offering both, when available.
That would be great to send via mail, messaging, etc. Even to other transmission servers, cloud torrenting services, media players, etc.

**Comment by y-polek** [comment]
8188647af9fbed87d2fb92f5fe11f5803a4ea606 - Added "Share Magnet Link" menu item on Torrent Details screen.

**Comment by pataquets** [comment]
Awesome, thanks!
Spanish string submitted on #107.
