### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by simba83** [y-polek/TransmissionRemote#95]
Hi, 
Im trying to build this project to make some test with a small amount of changes but i got into some problems while trying to compile the original master git.
I use Latest Android Studio (Win10 x64)
Is it not possible to compile a build without the api_keys.properties file?

`FAILURE: Build failed with an exception.

* Where:
Build file 'C:\StudioProjects\Transmission\app\build.gradle' line: 118

* What went wrong:
A problem occurred evaluating project ':app'.
> 'api_keys.properties' file does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
'api_keys.properties' file does not exist
Open File
16:39:05: Task execution finished.
`

**Comment by y-polek** [comment]
@simba83 to resolve this you have to add your own Fabric API key.
To do this:
1) Go to [Fabric install guide](https://fabric.io/kits/android/crashlytics/install), to the section "Add Your API Key" and login/sign up
2) Copy value of generated API Key from <meta-data> tag.
```
      <meta-data
          android:name="io.fabric.ApiKey"
          android:value="<FABRIC_API_KEY>"
      />
```
3) Create file `api_keys.properties` with following content in project root folder:
`fabric_api_key=FABRIC_API_KEY`
where `FABRIC_API_KEY` should be replaced with value copied from <meta-data> tag.
4) Sync Project again (File -> Sync Project with Gradle Files)

**Comment by simba83** [comment]
Thank you for the help, got things working.
